---
- hosts: all
  vars:
    gnome_extensions:
      - name: "user-theme@gnome-shell-extensions.gcampax.github.com"
        url: ""
      - name: "dash-to-panel@jderose9.github.com"
        url: "https://extensions.gnome.org/extension-data/dash-to-paneljderose9.github.com.v19.shell-extension.zip"
      - name: "arc-menu@linxgem33.com"
        url: "https://extensions.gnome.org/extension-data/arc-menulinxgem33.com.v24.shell-extension.zip"
  tasks:
    - name: Get Fedora version
      shell: rpm -E %fedora
      args:
        warn: false
      changed_when: false
      register: fedora_version
    - name: Add RPM Fusion repo
      dnf:
        name:
          - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version.stdout }}.noarch.rpm
          - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version.stdout }}.noarch.rpm
        state: present
      become: yes
    - name: Add google-chrome repo
      yum_repository:
        name: google-chrome
        description: google-chrome repo
        baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
        gpgcheck: yes
        gpgkey: https://dl.google.com/linux/linux_signing_key.pub
      become: yes
    - name: Upgrade all packages
      dnf:
        name: "*"
        state: latest
      become: yes
    - name: Remove packages
      dnf:
        name:
          - PackageKit-glib
        state: absent
      become: yes
    - name: Install packages
      dnf:
        name:
          - firefox
          - google-chrome-stable
          - vlc
          - terminator
          - vim
          - virt-manager
          - libvirt
          - qemu-kvm
          - gimp
          - inkscape
          - gnome-tweaks
          - gparted
          - wine
          - libselinux-python
          - f30-backgrounds-extras-gnome
          - python3-psutil
          - xorg-x11-utils
          - neofetch
          - youtube-dl
        state: present
      become: yes
    - name: Enable and start sshd
      systemd:
        name: sshd
        state: started
        enabled: yes
      become: yes
    - name: Ensure group libvirt exists
      group:
        name: libvirt
        state: present
      become: yes
    - name: Add {{ lookup('env','USER') }} to libvirt group
      user:
        name: "{{ lookup('env','USER') }}"
        groups: libvirt
        append: yes
      become: yes
    - name: Setup keyboard layouts
      dconf:
        key: "/org/gnome/desktop/input-sources/sources"
        value: "[('xkb', 'cz'), ('xkb', 'us'), ('xkb', 'sk+qwerty')]"
        state: present
    - name: Disable auto screen lock
      dconf:
        key: "/org/gnome/desktop/screensaver/lock-enabled"
        value: "false"
        state: present
    - name: Enable tap-to-click
      dconf:
        key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
        value: "true"
        state: present
    - name: Set clock format
      dconf:
        key: "/org/gnome/desktop/interface/clock-format"
        value: "'12h'"
        state: present
    - name: Set alt-tab
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-windows"
        value: "['<Alt>Tab']"
        state: present
    - name: Set alt-tab backward
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-windows-backward"
        value: "['<Shift><Alt>Tab']"
        state: present
    - name: Set super-tab
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-applications"
        value: "['<Super>Tab']"
        state: present
    - name: Set super-tab backward
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-applications-backward"
        value: "['<Shift><Super>Tab']"
        state: present
    - name: Create local extensions directory
      file:
        path: ~/.local/share/gnome-shell/extensions
        state: directory
    - name: Create extensions subdirs
      file:
        path: "~/.local/share/gnome-shell/extensions/{{ item.name }}"
        state: directory
      with_items:
        - "{{ gnome_extensions }}"
      when: item.url != ""
    - name: Download extensions
      unarchive:
        src: "{{ item.url }}"
        dest: "~/.local/share/gnome-shell/extensions/{{ item.name }}"
        remote_src: yes
      with_items:
        - "{{ gnome_extensions }}"
      when: item.url != ""
    - name: Enable extensions
      dconf:
        key: "/org/gnome/shell/enabled-extensions"
        value: "{{ a }}"
        state: present
      vars:
        a: "{{ gnome_extensions | map(attribute='name') | list }}"
    - name: Set bash line format
      lineinfile:
        path: ~/.bashrc
        regexp: ^PS1=
        line: |
            PS1="[\[\e[96m\]\u\[\e[0m\]: \W\$(git branch 2> /dev/null | grep \-e '\* ' | sed 's/^..\(.*\)/ \[\e[92m\](\1)\[\e[0m\]/')]\$ "

