---
- hosts: all
  vars:
    pycharm_url: https://download.jetbrains.com/python/pycharm-community-2018.2.4.tar.gz
    idea_url: https://download.jetbrains.com/idea/ideaIC-2018.2.5.tar.gz
    android_studio_url: https://dl.google.com/dl/android/studio/ide-zips/3.2.1.0/android-studio-ide-181.5056338-linux.zip
  tasks:
    - name: Add Slack repo
      yum_repository:
        name: slack
        description: slack repo
        baseurl: https://packagecloud.io/slacktechnologies/slack/fedora/21/$basearch
        gpgcheck: yes
        gpgkey: https://slack.com/gpg/slack_pubkey.gpg
      become: yes
    - name: Install packages
      dnf:
        name:
          - gitk
          - hexchat
          - wireshark-gtk
          - docker
          - docker-compose
          - origin-clients
          - slack
        state: present
      become: yes
    - name: Ensure group docker exists
      group:
        name: docker
        state: present
      become: yes
    - name: Add {{ lookup('env','USER') }} to docker group
      user:
        name: "{{ lookup('env','USER') }}"
        groups: docker
        append: yes
      become: yes
    - name: Enable and start docker
      systemd:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: Set Git name
      git_config:
        name: user.name
        value: Jan Dobes
        scope: global
    - name: Set Git email
      git_config:
        name: user.email
        value: git@owny.cz
        scope: global
    - name: Install JetBrains IDEs
      unarchive:
        src: "{{ item }}"
        dest: /opt
        remote_src: yes
      become: yes
      with_items:
        - "{{ pycharm_url }}"
        - "{{ idea_url }}"
        - "{{ android_studio_url }}"
