---
- hosts: all
  tasks:
    - name: Add Slack repo
      yum_repository:
        name: slack
        description: slack repo
        baseurl: https://packagecloud.io/slacktechnologies/slack/fedora/21/$basearch
        gpgcheck: yes
        gpgkey: https://slack.com/gpg/slack_pubkey_2019.gpg
      become: yes
    - name: Add VS Code repo
      yum_repository:
        name: vscode
        description: vscode repo
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgcheck: yes
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
      become: yes
    - name: Install packages
      dnf:
        name:
          - gitk
          - wireshark
          - podman
          - origin-clients
          - slack
          - code
        state: present
      become: yes
    - name: Set Git name
      git_config:
        name: user.name
        value: Jan Dobes
        scope: global
    - name: Set Git email
      git_config:
        name: user.email
        value: git@owny.cz
        scope: global

