---
- hosts: all
  vars:
  tasks:
    - name: Add Slack repo
      yum_repository:
        name: slack
        description: slack repo
        baseurl: https://packagecloud.io/slacktechnologies/slack/fedora/21/$basearch
        gpgcheck: yes
        gpgkey: https://slack.com/gpg/slack_pubkey.gpg
      become: yes
    - name: Install packages
      dnf:
        name:
          - gitk
          - hexchat
          - wireshark-gtk
          - docker
          - docker-compose
          - origin-clients
          - slack
        state: present
      become: yes
    - name: Enable and start docker
      systemd:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: Set Git name
      git_config:
        name: user.name
        value: Jan Dobes
        scope: global
    - name: Set Git email
      git_config:
        name: user.email
        value: git@owny.cz
        scope: global

