---
- hosts: all
  vars_files:
    - config/redhat.yml
  tasks:
    - name: Install openvpn packages
      dnf:
        name:
          - NetworkManager-openvpn
          - NetworkManager-openvpn-gnome
          - "{{ redhat_internal_cert }}"
          - "{{ redhat_internal_openvpn_profiles }}"
        state: present
      become: yes
    - name: Install kerberos packages
      dnf:
        name:
          - "{{ config_rpm_url }}"
        state: present
      become: yes
    - name: Get Firefox config path
      shell: find ~/.mozilla/firefox/ -type d -name '*.default'
      register: firefox_config_path
      changed_when: false
    - name: Set Firefox kerberos settings
      copy:
        src: config/firefox-kerberos.js
        dest: "{{ firefox_config_path.stdout }}/user.js"
      when: firefox_config_path.stdout != ""
    - name: Ensure /etc/opt/chrome/policies/managed dir exists
      file:
        path: /etc/opt/chrome/policies/managed
        state: directory
      become: yes
    - name: Set Chrome kerberos settings
      copy:
        src: config/google-chrome-kerberos.json
        dest: /etc/opt/chrome/policies/managed/redhat.json
      become: yes
    - name: Set hexchat server list
      copy:
        src: config/hexchat-servlist.conf
        dest: ~/.config/hexchat/servlist.conf
    - name: Configure printers 1/3
      lineinfile:
        path: /etc/cups/cups-browsed.conf
        regexp: ^BrowsePoll
        line: BrowsePoll {{ cups_server }}
      become: yes
    - name: Configure printers 2/3
      lineinfile:
        path: /etc/cups/cups-browsed.conf
        regexp: ^LocalQueueNamingRemoteCUPS
        line: LocalQueueNamingRemoteCUPS RemoteName
      become: yes
    - name: Configure printers 3/3
      systemd:
        name: cups-browsed
        state: restarted
        enabled: yes
      become: yes
